### PR TITLE
Add code for extraction of library dependent repos 

### PR DESCRIPTION
**Pull request by zurk**

### CODE REVIEW

**Comment by bzz** [comment]
Does it use https://libraries.io/data? Nice!

Util something like https://github.com/epochx/commitgen works well - it's usually a good engineering practice to have a short summary of your changes in PR description.

It's also saves time for reviewers when changes have well-defined test plan: exact instructions on how they intended to be used/triggered. I.e in case of CLI it could be a series of shell commands a user must run on his local environment (assuming he is not super-familiar with the project internals) to test the changes: get input data (`wget ...`), how to process, and what the expected output is.

**Comment by zurk** [comment]
Yes, this code use https://libraries.io database.
Thank you @bzz for good links and explanation how it should be. 
I will check this tool.

I think that now all this code under active development and everything can be changed.
As you see, it is just python scripts. I need to add tests, CLI, README, etc.
I take care of it soon.

My bad that I begin to do it in master, now I switch to develop.

**Comment by vmarkovtsev** [comment]
@zurk It is fine to do this project in master branch, as it is experimental.

**Comment by zurk** [comment]
Ok, I will continue to work in the master branch then. 
And this PR is not actual anymore, so I close it.
Here is new one https://github.com/src-d/snippet-ranger/pull/4.

**Pull request closed without merging**
